//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsharpMacros.Test.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsharpMacros.Test.General.TestCases", typeof(TestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///
        ///        public void DoSth()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 32
        ///            };
        ///            //[|macros.properti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_WithSingleFilter {
            get {
                return ResourceManager.GetString("_001_WithSingleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///
        ///        public void DoSth()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 32
        ///            };
        ///            Assert.AreNotEqual( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_WithSIngleFilter_FIXED {
            get {
                return ResourceManager.GetString("_001_WithSIngleFilter_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///
        ///        public void DoSth()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 32
        ///            };
        ///            //[|macros.properti [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_WithMultipleFilters {
            get {
                return ResourceManager.GetString("_002_WithMultipleFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///
        ///        public void DoSth()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 32
        ///            };
        ///            Assert.AreNotEqual( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_WIthMultipleFIlters_FIXED {
            get {
                return ResourceManager.GetString("_002_WIthMultipleFIlters_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 32
        ///            };
        ///            // Sample comment abo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_CommentAboveTheMacro {
            get {
                return ResourceManager.GetString("_003_CommentAboveTheMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            var user = new UserDTO()
        ///            {
        ///                FirstName = &quot;John&quot;,
        ///                LastName = &quot;Doe&quot;,
        ///                Age = 32
        ///            };
        ///            // Sample comment abo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _003_CommentAboveTheMacro_FIXED {
            get {
                return ResourceManager.GetString("_003_CommentAboveTheMacro_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            //[|macros.properties(UserDTO)|]
        ///            //Console.WriteLine(&quot;${name}&quot;);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _004_WhenMacroIsSingleExpressionInMethod {
            get {
                return ResourceManager.GetString("_004_WhenMacroIsSingleExpressionInMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            Console.WriteLine(&quot;FirstName&quot;);
        ///            Console.WriteLine(&quot;LastName&quot;);
        ///            Console.WriteLine(&quot;Age&quot;);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _004_WhenMacroIsSingleExpressionInMethod_FIXED {
            get {
                return ResourceManager.GetString("_004_WhenMacroIsSingleExpressionInMethod_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            //[|macros.properties(UserDTO)|]
        ///            //Console.WriteLine(&quot;${name}&quot;);
        ///            Console.WriteLine(&quot;!!!END!!!&quot;);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _005_WhenMacroIsFirstExpressionInMethod {
            get {
                return ResourceManager.GetString("_005_WhenMacroIsFirstExpressionInMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            Console.WriteLine(&quot;FirstName&quot;);
        ///            Console.WriteLine(&quot;LastName&quot;);
        ///            Console.WriteLine(&quot;Age&quot;);
        ///            Console.WriteLine(&quot;!!!END!!!&quot;);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _005_WhenMacroIsFirstExpressionInMethod_FIXED {
            get {
                return ResourceManager.GetString("_005_WhenMacroIsFirstExpressionInMethod_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            Console.WriteLine(&quot;!!!BEGIN!!!&quot;);
        ///            //[|macros.properties(UserDTO)|]
        ///            //Console.WriteLine(&quot;${name}&quot;);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _006_WhenMacroIsLastExpressionInMethod {
            get {
                return ResourceManager.GetString("_006_WhenMacroIsLastExpressionInMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            Console.WriteLine(&quot;!!!BEGIN!!!&quot;);
        ///            Console.WriteLine(&quot;FirstName&quot;);
        ///            Console.WriteLine(&quot;LastName&quot;);
        ///            Console.WriteLine(&quot;Age&quot;);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _006_WhenMacroIsLastExpressionInMethod_FIXED {
            get {
                return ResourceManager.GetString("_006_WhenMacroIsLastExpressionInMethod_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            if(true)
        ///            {
        ///                //[|macros.properties(UserDTO)|]
        ///                //Console.WriteLine(&quot;${name}&quot;);
        ///            }
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _007_WhenMacroIsInsideIf_ {
            get {
                return ResourceManager.GetString("_007_WhenMacroIsInsideIf_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            if(true)
        ///            {
        ///                Console.WriteLine(&quot;FirstName&quot;);
        ///                Console.WriteLine(&quot;LastName&quot;);
        ///                Console.WriteLine(&quot;Age&quot;);
        ///            }
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _007_WhenMacroIsInsideIf_FIXED {
            get {
                return ResourceManager.GetString("_007_WhenMacroIsInsideIf_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            if(true)
        ///                //[|macros.properties(UserDTO)|]
        ///                //Console.WriteLine(&quot;${name}&quot;);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _008_WhenMacroIsInsideIfWithoutBracket {
            get {
                return ResourceManager.GetString("_008_WhenMacroIsInsideIfWithoutBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///    }
        ///
        ///    class _001_ObjectWithOwnProperties
        ///    {
        ///        public void DoSth()
        ///        {
        ///            if(true)
        ///                Console.WriteLine(&quot;FirstName&quot;);
        ///                Console.WriteLine(&quot;LastName&quot;);
        ///                Console.WriteLine(&quot;Age&quot;);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _008_WhenMacroIsInsideIfWithoutBracket_FIXED {
            get {
                return ResourceManager.GetString("_008_WhenMacroIsInsideIfWithoutBracket_FIXED", resourceCulture);
            }
        }
    }
}
