//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsharpMacros.Test.Macros.Methods {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CsharpMacros.Test.Macros.Methods.TestCases", typeof(TestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///
        ///        public int DoSth1(int a)
        ///        {
        ///            return 1;
        ///        }
        ///        
        ///        public string DoSth2(string b)
        ///        {
        ///            return &quot;&quot;;
        ///        }
        ///    }
        ///
        ///    class _001_ObjectWithOwnMethods
        ///    {
        ///
        ///        public void DoSth()
        ///        {
        ///            var user = n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_ObjectWithOwnMethods {
            get {
                return ResourceManager.GetString("_001_ObjectWithOwnMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///
        ///        public int DoSth1(int a)
        ///        {
        ///            return 1;
        ///        }
        ///        
        ///        public string DoSth2(string b)
        ///        {
        ///            return &quot;&quot;;
        ///        }
        ///    }
        ///
        ///    class _001_ObjectWithOwnMethods
        ///    {
        ///
        ///        public void DoSth()
        ///        {
        ///            var user = n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _001_ObjectWithOwnMethods_FIXED {
            get {
                return ResourceManager.GetString("_001_ObjectWithOwnMethods_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///
        ///        public void DoSth1(int a)
        ///        {
        ///        }
        ///        
        ///        public void DoSth2(string b)
        ///        {
        ///        }
        ///    }
        ///
        ///    class _001_ObjectWithOwnMethods
        ///    {
        ///
        ///        public void DoSth()
        ///        {
        ///            var user = new UserDTO();
        ///            //[|macros.methods(Us [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_ObjectWithVoidMethod {
            get {
                return ResourceManager.GetString("_002_ObjectWithVoidMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    class UserDTO
        ///    {
        ///        public string FirstName { get; set; }
        ///        public string LastName { get; set; }
        ///        public int Age { get; set; }
        ///
        ///        public void DoSth1(int a)
        ///        {
        ///        }
        ///        
        ///        public void DoSth2(string b)
        ///        {
        ///        }
        ///    }
        ///
        ///    class _001_ObjectWithOwnMethods
        ///    {
        ///
        ///        public void DoSth()
        ///        {
        ///            var user = new UserDTO();
        ///            var paramForDoSth1 =  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _002_ObjectWithVoidMethod_FIXED {
            get {
                return ResourceManager.GetString("_002_ObjectWithVoidMethod_FIXED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    interface IDoer
        ///    {
        ///        public int DoSth1(int a);
        ///        
        ///        public void DoSth2(string b, int b);
        ///    }
        ///
        ///    class _001_Doer: IDoer
        ///    {
        ///        private readonlu IDoer underlyingDoer;
        ///
        ///        //[|macros.methods(IDoer)|]
        ///        //${signature}
        ///        //{
        ///        //  ${returnOperator} underlyingDoer.${name}(${parameters});
        ///        //}
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _003_ImplementingProxy {
            get {
                return ResourceManager.GetString("_003_ImplementingProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace CsharpMacros.Test.Macros.Properties.TestData
        ///{
        ///    interface IDoer
        ///    {
        ///        public int DoSth1(int a);
        ///        
        ///        public void DoSth2(string b, int b);
        ///    }
        ///
        ///    class _001_Doer: IDoer
        ///    {
        ///        private readonlu IDoer underlyingDoer;
        ///
        ///        public int DoSth1(int a)
        ///        {
        ///            return underlyingDoer.DoSth1(a);
        ///        }
        ///        
        ///        public void DoSth2(string b, int b)
        ///        {
        ///            underlyingDoer.DoSth2(a);
        ///        }
        ///    }
        ///}
        ///.
        /// </summary>
        internal static string _003_ImplementingProxy_FIXED {
            get {
                return ResourceManager.GetString("_003_ImplementingProxy_FIXED", resourceCulture);
            }
        }
    }
}
